import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Lightbulb, Save, RefreshCw, Building2, FileText, ChevronDown, ChevronUp, ArrowRight, Sparkles, ArrowLeft, Download, Target, Presentation, Banknote, Briefcase, Users, TrendingUp, AlertTriangle, Share2, Bot } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { useAI } from '../hooks/useAI';
import { useFirestore } from '../hooks/useFirestore';
import useAuthStore from '../store/authStore';
import { getScoreColor, getScoreLabel } from '../lib/utils';
import ErrorMessage from '../components/shared/ErrorMessage';
import LoadingSpinner from '../components/shared/LoadingSpinner';
import EmptyState from '../components/shared/EmptyState';
import { Toast, useToast } from '../components/shared/SuccessToast';

export default function IdeaValidator() {
  const [currentStep, setCurrentStep] = useState(1);
  const [wizardData, setWizardData] = useState({
    problem: '',
    solution: '',
    targetMarket: '',
    unfairAdvantage: '',
    budget: '',
    location: ''
  });
  
  const [result, setResult] = useState(null);
  
  const [savedIdeas, setSavedIdeas] = useState([]);
  const [expandedIdea, setExpandedIdea] = useState(null);
  
  const { validateBusinessIdea, loading, error } = useAI();
  const { addDocument, getUserDocuments } = useFirestore();
  const { userProfile } = useAuthStore();
  const { toast, show, hide } = useToast();
  const navigate = useNavigate();

  useEffect(() => {
    loadSavedIdeas();
  }, []);



  async function loadSavedIdeas() {
    const ideas = await getUserDocuments('businessIdeas');
    setSavedIdeas(ideas);
  }

  function handleNextStep() {
    if (currentStep < 5) setCurrentStep(c => c + 1);
  }

  function handlePrevStep() {
    if (currentStep > 1) setCurrentStep(c => c - 1);
  }

  async function handleValidate() {
    try {
      const responseJson = await validateBusinessIdea(wizardData);
      setResult(responseJson);
      
      const compiledIdeaText = `Problem: ${wizardData.problem}\nSolution: ${wizardData.solution}\nTarget Market: ${wizardData.targetMarket}\nUnfair Advantage: ${wizardData.unfairAdvantage}`;
      
      // Save pipeline data globally for other tools
      localStorage.setItem('impunga_idea_pipeline', JSON.stringify({
        ideaText: compiledIdeaText,
        aiAnalysis: JSON.stringify(responseJson, null, 2),
        viabilityScore: responseJson.score,
        location: wizardData.location,
        budget: wizardData.budget,
        timestamp: Date.now(),
      }));
    } catch (err) {
      console.error(err);
    }
  }

  async function handleSave() {
    if (!result) return;
    try {
      await addDocument('businessIdeas', {
        wizardData,
        score: result.score,
        verdict: result.verdict,
        result: result,
        timestamp: Date.now()
      });
      show('Idea analysis saved to your profile!');
      loadSavedIdeas();
    } catch (err) {
      show('Failed to save. Please try again.', 'error');
    }
  }

  function handleReset() {


    setWizardData({
      problem: '',
      solution: '',
      targetMarket: '',
      unfairAdvantage: '',
      budget: '',
      location: ''
    });
    setResult(null);
    setCurrentStep(1);
  }



  function handleDownloadPDF() {
    if (!result) return;
    const doc = new jsPDF();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('Startup Blueprint & Analysis', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Generated by IMPUNGA Startup Studio', 105, 28, { align: 'center' });
    
    doc.setDrawColor(200);
    doc.line(20, 35, 190, 35);
    
    let yPos = 45;
    const addSection = (title, content) => {
      if (!content) return;
      if (yPos > 270) { doc.addPage(); yPos = 20; }
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text(title, 20, yPos);
      yPos += 7;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50);
      const lines = doc.splitTextToSize(content, 170);
      doc.text(lines, 20, yPos);
      yPos += (lines.length * 5) + 10;
    };

    addSection('Executive Summary', result.executiveSummary);
    addSection('Viability Score', `${result.score}/10 - ${result.verdict}`);
    addSection('Unit Economics', result.unitEconomics);
    addSection('Competitor Intelligence', result.competitorIntel);
    addSection('Capital Allocation', result.capitalAllocation);
    addSection('Risk Assessment', result.riskAssessment);
    if (result.consultantPivot) {
      addSection('Consultant Strategy', result.consultantPivot);
    }
    
    doc.save('Startup_Blueprint.pdf');
    show('Blueprint PDF downloaded successfully!');
  }

  const isStepValid = () => {
    switch(currentStep) {
      case 1: return wizardData.problem.length >= 10;
      case 2: return wizardData.solution.length >= 20;
      case 3: return wizardData.targetMarket.length >= 10;
      case 4: return wizardData.unfairAdvantage.length >= 10;
      case 5: return wizardData.budget.length >= 2 && wizardData.location.length >= 2;
      default: return false;
    }
  };

  const renderWizardStep = () => {
    switch(currentStep) {
      case 1:
        return (
          <div className="animate-fade-in">
            <h3 className="text-xl font-bold text-gray-800 mb-2">1. The Problem</h3>
            <p className="text-sm text-gray-500 mb-4">What specific problem are you solving for Zambians?</p>
            <textarea
              value={wizardData.problem}
              onChange={e => setWizardData({...wizardData, problem: e.target.value})}
              placeholder="e.g., People in my area have to travel 10km to buy fresh vegetables..."
              className="w-full p-4 bg-gray-50 border border-gray-200 rounded-2xl h-32 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all resize-none"
            />
          </div>
        );
      case 2:
        return (
          <div className="animate-fade-in">
            <h3 className="text-xl font-bold text-gray-800 mb-2">2. The Solution</h3>
            <p className="text-sm text-gray-500 mb-4">How does your business solve this problem? (The Idea)</p>
            <textarea
              value={wizardData.solution}
              onChange={e => setWizardData({...wizardData, solution: e.target.value})}
              placeholder="e.g., I will open a cold-storage farm stand in the neighbourhood center..."
              className="w-full p-4 bg-gray-50 border border-gray-200 rounded-2xl h-32 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all resize-none"
            />
          </div>
        );
      case 3:
        return (
          <div className="animate-fade-in">
            <h3 className="text-xl font-bold text-gray-800 mb-2">3. Target Market</h3>
            <p className="text-sm text-gray-500 mb-4">Who exactly will pay for this? Be specific about demographics.</p>
            <textarea
              value={wizardData.targetMarket}
              onChange={e => setWizardData({...wizardData, targetMarket: e.target.value})}
              placeholder="e.g., Working mothers aged 25-45 who value convenience and health..."
              className="w-full p-4 bg-gray-50 border border-gray-200 rounded-2xl h-32 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all resize-none"
            />
          </div>
        );
      case 4:
        return (
          <div className="animate-fade-in">
            <h3 className="text-xl font-bold text-gray-800 mb-2">4. Your Unfair Advantage</h3>
            <p className="text-sm text-gray-500 mb-4">What experience, network, or resources do you have that others don't?</p>
            <textarea
              value={wizardData.unfairAdvantage}
              onChange={e => setWizardData({...wizardData, unfairAdvantage: e.target.value})}
              placeholder="e.g., My uncle owns a farm so I can get stock at 30% discount..."
              className="w-full p-4 bg-gray-50 border border-gray-200 rounded-2xl h-32 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all resize-none"
            />
          </div>
        );
      case 5:
        return (
          <div className="animate-fade-in space-y-4">
            <h3 className="text-xl font-bold text-gray-800 mb-2">5. The Capital & Location</h3>
            <p className="text-sm text-gray-500 mb-4">What resources are you starting with?</p>
            
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Starting Budget (ZMW)</label>
              <input
                type="text"
                value={wizardData.budget}
                onChange={e => setWizardData({...wizardData, budget: e.target.value})}
                placeholder="e.g., K10,000"
                className="w-full p-4 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Primary Location</label>
              <input
                type="text"
                value={wizardData.location}
                onChange={e => setWizardData({...wizardData, location: e.target.value})}
                placeholder="e.g., Lusaka CBD / Online / Rural Ndola"
                className="w-full p-4 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all"
              />
            </div>
          </div>
        );
      default: return null;
    }
  }

  return (
    <div className="max-w-4xl mx-auto pb-24 animate-fade-in">
      {toast.isVisible && <Toast message={toast.message} type={toast.type} onClose={hide} />}

      <button onClick={() => navigate(-1)} className="inline-flex items-center gap-2 text-sm font-medium text-gray-500 hover:text-gray-800 mb-6 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Back to Dashboard
      </button>

      <div className="mb-8">
        <h1 className="text-4xl font-extrabold text-gray-900 tracking-tight mb-2 flex items-center gap-3">
          <Sparkles className="w-8 h-8 text-indigo-600" /> Startup Studio
        </h1>
        <p className="text-gray-500 font-medium text-lg">Validate your idea and generate a strategic blueprint.</p>
      </div>

      {!result && (
        <div className="bg-white/85 backdrop-blur-3xl border border-white/60 shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-3xl p-6 sm:p-8 mb-8 relative overflow-hidden">
          <div className="flex items-center gap-2 mb-8">
            {[1, 2, 3, 4, 5].map(step => (
              <div key={step} className="flex-1 h-2 rounded-full bg-gray-100 overflow-hidden">
                <div className={step <= currentStep ? "h-full bg-indigo-600 transition-all duration-300" : "h-full bg-transparent transition-all duration-300"} />
              </div>
            ))}
          </div>

          {error && <ErrorMessage message={error} />}

          <div className="min-h-[250px]">
            {renderWizardStep()}
          </div>

          <div className="flex items-center justify-between mt-8 pt-6 border-t border-gray-100">
            <button
              onClick={handlePrevStep}
              disabled={currentStep === 1 || loading}
              className="px-6 py-3 text-gray-500 font-semibold disabled:opacity-30 hover:text-gray-800 transition-colors"
            >
              Back
            </button>
            
            {currentStep < 5 ? (
              <button
                onClick={handleNextStep}
                disabled={!isStepValid()}
                className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold px-8 py-3 rounded-xl transition-all active:scale-95 disabled:opacity-50 flex items-center gap-2"
              >
                Next <ArrowRight className="w-4 h-4" />
              </button>
            ) : (
              <button
                onClick={handleValidate}
                disabled={!isStepValid() || loading}
                className="bg-gradient-to-r from-yellow-500 to-yellow-600 hover:from-yellow-600 hover:to-yellow-700 text-white font-bold px-8 py-3 rounded-xl transition-all shadow-lg shadow-yellow-500/30 active:scale-95 disabled:opacity-50 flex items-center gap-2"
              >
                {loading ? <><LoadingSpinner size="sm" /> Analyzing...</> : <><Sparkles className="w-5 h-5" /> Generate Blueprint</>}
              </button>
            )}
          </div>
        </div>
      )}

      {/* Blueprint Results Dashboard */}
      {result && (
        <div className="bg-transparent animate-slide-up space-y-6">
          {/* Header Card */}
          <div className="bg-white rounded-3xl p-8 border border-gray-100 shadow-sm relative overflow-hidden overflow-x-auto">
            <div className={"absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-20 -mr-20 -mt-20 " + (result.score >= 6 ? 'bg-green-400' : 'bg-yellow-400')} />
            
            <div className="flex items-center justify-between mb-4 relative z-10">
              <span className={`inline-flex items-center px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wider ${
                result.verdict === 'PROCEED' ? 'bg-green-100 text-green-800' :
                result.verdict === 'REFINE' ? 'bg-yellow-100 text-yellow-800' :
                'bg-red-100 text-red-800'
              }`}>{result.verdict}</span>
              
              <div className="flex items-center gap-2">
                <span className="text-4xl font-black text-gray-900">{result.score}</span>
                <span className="text-xl text-gray-400 font-bold">/10</span>
              </div>
            </div>
            
            <h2 className="text-2xl font-bold text-gray-900 mb-2 relative z-10">{result.executiveSummary}</h2>
            <p className="text-gray-500 font-medium relative z-10">AI Viability Score based on unit economics and market demand.</p>
          </div>

          {/* Core Analysis Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center"><TrendingUp className="w-5 h-5" /></div>
                <h3 className="font-bold text-gray-900 text-lg">Unit Economics</h3>
              </div>
              <p className="text-gray-600 leading-relaxed">{result.unitEconomics}</p>
            </div>

            <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 bg-purple-50 text-purple-600 rounded-xl flex items-center justify-center"><Users className="w-5 h-5" /></div>
                <h3 className="font-bold text-gray-900 text-lg">Competitor Intel</h3>
              </div>
              <p className="text-gray-600 leading-relaxed">{result.competitorIntel}</p>
            </div>

            <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center"><Banknote className="w-5 h-5" /></div>
                <h3 className="font-bold text-gray-900 text-lg">Capital Allocation</h3>
              </div>
              <p className="text-gray-600 leading-relaxed">{result.capitalAllocation}</p>
            </div>

            <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 bg-red-50 text-red-600 rounded-xl flex items-center justify-center"><AlertTriangle className="w-5 h-5" /></div>
                <h3 className="font-bold text-gray-900 text-lg">Risk Assessment</h3>
              </div>
              <p className="text-gray-600 leading-relaxed">{result.riskAssessment}</p>
            </div>
          </div>

          {/* Consultant Pivot (Only if score <= 5) */}
          {result.score <= 5 && result.consultantPivot && (
            <div className="bg-orange-50 rounded-3xl p-8 border border-orange-200 shadow-sm">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 bg-orange-100 text-orange-600 rounded-xl flex items-center justify-center"><Briefcase className="w-5 h-5" /></div>
                <h3 className="font-bold text-orange-900 text-xl">Consultant's Pivot Strategy</h3>
              </div>
              <p className="text-orange-800 leading-relaxed text-lg">{result.consultantPivot}</p>
            </div>
          )}



          {/* Actions Bar */}
          <div className="flex gap-3 bg-white p-4 rounded-2xl border border-gray-100 shadow-sm whitespace-nowrap overflow-x-auto">
            <button onClick={handleSave} className="flex items-center gap-2 bg-gray-100 hover:bg-gray-200 text-gray-800 font-semibold text-sm px-5 py-2.5 rounded-xl transition-colors active:scale-95">
              <Save className="w-4 h-4" /> Save
            </button>
            <button onClick={handleDownloadPDF} className="flex items-center gap-2 bg-gray-100 hover:bg-gray-200 text-gray-800 font-semibold text-sm px-5 py-2.5 rounded-xl transition-colors active:scale-95">
              <Download className="w-4 h-4" /> PDF
            </button>
            <button onClick={handleReset} className="flex items-center gap-2 bg-white border border-gray-200 hover:bg-gray-50 text-gray-600 font-semibold text-sm px-5 py-2.5 rounded-xl transition-colors active:scale-95">
              <RefreshCw className="w-4 h-4" /> New Idea
            </button>
          </div>

          {/* AI Co-Founder Banner */}
          <Link to="/ai-advisor" className="block bg-gradient-to-r from-indigo-600 to-violet-600 rounded-3xl p-6 sm:p-8 relative overflow-hidden group hover:shadow-lg hover:shadow-indigo-500/30 transition-all">
            <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl -mr-10 -mt-20 group-hover:bg-white/20 transition-colors" />
            <div className="flex items-center gap-6 relative z-10">
              <div className="w-16 h-16 bg-white/10 backdrop-blur-md rounded-2xl flex items-center justify-center shrink-0 border border-white/20 group-hover:scale-105 transition-transform">
                <Bot className="w-8 h-8 text-white" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-white mb-1">Chat with your AI Co-Founder</h3>
                <p className="text-indigo-100 font-medium text-sm md:text-base">Your Co-Founder has analyzed this Blueprint and is ready to help you execute it.</p>
              </div>
              <ArrowRight className="w-6 h-6 text-white ml-auto group-hover:translate-x-2 transition-transform" />
            </div>
          </Link>
          
          {/* Next Steps Pipeline */}
          <div className="bg-white rounded-3xl p-8 border border-gray-100 shadow-sm mt-8">
            <div className="flex items-center gap-3 mb-6">
              <div className={"w-10 h-10 rounded-full flex items-center justify-center shrink-0 " + (result.score >= 6 ? 'bg-green-100 text-green-600' : 'bg-yellow-100 text-yellow-600')}>
                <Sparkles className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-gray-900">
                  {result.score >= 6 ? 'Your Idea is Viable! Next Steps:' : 'Your Idea Needs Refinement. To proceed, explore these tools:'}
                </h3>
                <p className="text-sm text-gray-500">
                  {result.score >= 6 ? 'Follow this pipeline to launch your business properly.' : 'Use the pivot strategy above, then build your roadmap here.'}
                </p>
              </div>
            </div>
            
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
              <Link to="/name-generator" className="group flex items-center justify-between p-4 bg-gray-50 border border-gray-100 rounded-2xl hover:border-blue-200 hover:shadow-md transition-all">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-blue-100 text-blue-600 rounded-xl flex items-center justify-center"><Sparkles className="w-5 h-5" /></div>
                  <div><h4 className="font-bold text-gray-900 group-hover:text-blue-600 transition-colors">1. Name Generator</h4><p className="text-xs text-gray-500">Get a brand name</p></div>
                </div>
                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-blue-600 transition-colors" />
              </Link>
              
              <Link to="/swot-analysis" className="group flex items-center justify-between p-4 bg-gray-50 border border-gray-100 rounded-2xl hover:border-cyan-200 hover:shadow-md transition-all">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-cyan-100 text-cyan-600 rounded-xl flex items-center justify-center"><Target className="w-5 h-5" /></div>
                  <div><h4 className="font-bold text-gray-900 group-hover:text-cyan-600 transition-colors">2. SWOT Analysis</h4><p className="text-xs text-gray-500">Know your risks</p></div>
                </div>
                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-cyan-600 transition-colors" />
              </Link>
              
              <Link to="/business-plan" className="group flex items-center justify-between p-4 bg-gray-50 border border-gray-100 rounded-2xl hover:border-indigo-200 hover:shadow-md transition-all">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-indigo-100 text-indigo-600 rounded-xl flex items-center justify-center"><FileText className="w-5 h-5" /></div>
                  <div><h4 className="font-bold text-gray-900 group-hover:text-indigo-600 transition-colors">3. Business Plan</h4><p className="text-xs text-gray-500">Build the roadmap</p></div>
                </div>
                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-indigo-600 transition-colors" />
              </Link>

              <Link to="/registration-guide" className="group flex items-center justify-between p-4 bg-gray-50 border border-gray-100 rounded-2xl hover:border-emerald-200 hover:shadow-md transition-all">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-emerald-100 text-emerald-600 rounded-xl flex items-center justify-center"><Building2 className="w-5 h-5" /></div>
                  <div><h4 className="font-bold text-gray-900 group-hover:text-emerald-600 transition-colors">4. Formalise Setup</h4><p className="text-xs text-gray-500">PACRA & ZRA Guide</p></div>
                </div>
                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-emerald-600 transition-colors" />
              </Link>

              <Link to="/pitch-deck" className="group flex items-center justify-between p-4 bg-gray-50 border border-gray-100 rounded-2xl hover:border-fuchsia-200 hover:shadow-md transition-all">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-fuchsia-100 text-fuchsia-600 rounded-xl flex items-center justify-center"><Presentation className="w-5 h-5" /></div>
                  <div><h4 className="font-bold text-gray-900 group-hover:text-fuchsia-600 transition-colors">5. Pitch Deck</h4><p className="text-xs text-gray-500">For investors</p></div>
                </div>
                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-fuchsia-600 transition-colors" />
              </Link>
              
              <Link to="/funding-matchmaker" className="group flex items-center justify-between p-4 bg-gray-50 border border-gray-100 rounded-2xl hover:border-teal-200 hover:shadow-md transition-all">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-teal-100 text-teal-600 rounded-xl flex items-center justify-center"><Banknote className="w-5 h-5" /></div>
                  <div><h4 className="font-bold text-gray-900 group-hover:text-teal-600 transition-colors">6. Funding Matches</h4><p className="text-xs text-gray-500">Grants & Loans</p></div>
                </div>
                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-teal-600 transition-colors" />
              </Link>
              
              <Link to="/social-media" className="group flex items-center justify-between p-4 bg-gray-50 border border-gray-100 rounded-2xl hover:border-pink-200 hover:shadow-md transition-all">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-pink-100 text-pink-600 rounded-xl flex items-center justify-center"><Share2 className="w-5 h-5" /></div>
                  <div><h4 className="font-bold text-gray-900 group-hover:text-pink-600 transition-colors">7. Social Media</h4><p className="text-xs text-gray-500">Marketing Strategy</p></div>
                </div>
                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-pink-600 transition-colors" />
              </Link>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
