import { useState } from 'react';
import { Receipt, Plus, Trash2, Download } from 'lucide-react';
import { formatKwacha } from '../lib/utils';
import useAuthStore from '../store/authStore';
import { Toast, useToast } from '../components/shared/SuccessToast';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function InvoiceGenerator() {
  const { userProfile } = useAuthStore();
  const { toast, show, hide } = useToast();

  const [invoice, setInvoice] = useState({
    invoiceNumber: `INV-${Date.now().toString().slice(-5)}`,
    date: new Date().toISOString().split('T')[0],
    dueDate: '',
    businessName: userProfile?.businessName || '',
    businessPhone: '',
    businessEmail: '',
    businessAddress: '',
    clientName: '',
    clientPhone: '',
    clientAddress: '',
    items: [{ description: '', quantity: 1, unitPrice: '' }],
    notes: '',
    includeTax: false,
    taxRate: 16,
  });

  function update(field, value) {
    setInvoice(prev => ({ ...prev, [field]: value }));
  }

  function addItem() {
    setInvoice(prev => ({ ...prev, items: [...prev.items, { description: '', quantity: 1, unitPrice: '' }] }));
  }

  function removeItem(i) {
    setInvoice(prev => ({ ...prev, items: prev.items.filter((_, idx) => idx !== i) }));
  }

  function updateItem(i, field, value) {
    setInvoice(prev => {
      const items = [...prev.items];
      items[i] = { ...items[i], [field]: value };
      return { ...prev, items };
    });
  }

  const subtotal = invoice.items.reduce((sum, item) => sum + ((parseFloat(item.unitPrice) || 0) * (parseFloat(item.quantity) || 0)), 0);
  const tax = invoice.includeTax ? subtotal * (invoice.taxRate / 100) : 0;
  const total = subtotal + tax;

  function generatePDF() {
    const doc = new jsPDF();
    const primary = [27, 79, 114];
    const gold = [183, 149, 11];

    // Header
    doc.setFillColor(...primary);
    doc.rect(0, 0, 210, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont(undefined, 'bold');
    doc.text('INVOICE', 14, 16);
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Invoice #: ${invoice.invoiceNumber}`, 14, 24);
    doc.text(`Date: ${invoice.date}`, 14, 30);
    if (invoice.dueDate) doc.text(`Due: ${invoice.dueDate}`, 80, 30);

    // IMPUNGA branding
    doc.setFontSize(9);
    doc.setTextColor(180, 220, 255);
    doc.text('Generated by IMPUNGA', 150, 24);
    doc.text('impunga.vercel.app', 155, 30);

    // Business & Client info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('FROM:', 14, 48);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(invoice.businessName || 'Your Business Name', 14, 55);
    if (invoice.businessPhone) doc.text(`Tel: ${invoice.businessPhone}`, 14, 61);
    if (invoice.businessEmail) doc.text(invoice.businessEmail, 14, 67);
    if (invoice.businessAddress) doc.text(invoice.businessAddress, 14, 73);

    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('BILL TO:', 110, 48);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(invoice.clientName || 'Client Name', 110, 55);
    if (invoice.clientPhone) doc.text(`Tel: ${invoice.clientPhone}`, 110, 61);
    if (invoice.clientAddress) doc.text(invoice.clientAddress, 110, 67);

    // Items table
    const tableRows = invoice.items.map(item => [
      item.description || '-',
      item.quantity,
      formatKwacha(parseFloat(item.unitPrice) || 0),
      formatKwacha((parseFloat(item.unitPrice) || 0) * (parseFloat(item.quantity) || 0)),
    ]);

    autoTable(doc, {
      startY: 85,
      head: [['Description', 'Qty', 'Unit Price', 'Total']],
      body: tableRows,
      headStyles: { fillColor: primary, textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 247, 249] },
      columnStyles: { 0: { cellWidth: 90 }, 1: { halign: 'center' }, 2: { halign: 'right' }, 3: { halign: 'right' } },
    });

    const finalY = doc.lastAutoTable.finalY + 8;

    // Totals
    doc.setFontSize(10);
    doc.text('Subtotal:', 140, finalY);
    doc.text(formatKwacha(subtotal), 196, finalY, { align: 'right' });

    if (invoice.includeTax) {
      doc.text(`VAT (${invoice.taxRate}%):`, 140, finalY + 7);
      doc.text(formatKwacha(tax), 196, finalY + 7, { align: 'right' });
    }

    doc.setFillColor(...primary);
    doc.rect(130, finalY + (invoice.includeTax ? 12 : 5), 70, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont(undefined, 'bold');
    doc.text('TOTAL:', 134, finalY + (invoice.includeTax ? 19 : 12));
    doc.text(formatKwacha(total), 196, finalY + (invoice.includeTax ? 19 : 12), { align: 'right' });

    // Notes
    if (invoice.notes) {
      doc.setTextColor(0, 0, 0);
      doc.setFont(undefined, 'normal');
      doc.setFontSize(9);
      doc.text('Notes:', 14, finalY + 30);
      doc.text(invoice.notes, 14, finalY + 37);
    }

    // Footer
    doc.setTextColor(150);
    doc.setFontSize(8);
    doc.text('Thank you for your business! | Generated by IMPUNGA — Start. Match. Build Zambia.', 105, 285, { align: 'center' });

    doc.save(`Invoice_${invoice.invoiceNumber}_${invoice.clientName || 'Client'}.pdf`);
    show('Invoice downloaded!');
  }

  return (
    <div className="max-w-3xl mx-auto animate-fade-in">
      {toast && <Toast message={toast.message} type={toast.type} onClose={hide} />}

      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 bg-green-50 rounded-lg flex items-center justify-center">
          <Receipt className="w-5 h-5 text-accent-green" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Invoice Generator</h1>
          <p className="text-gray-500 text-sm">Create professional invoices in Kwacha and download as PDF</p>
        </div>
      </div>

      {/* Invoice details */}
      <div className="card mb-4">
        <h2 className="font-bold text-gray-800 mb-4">Invoice Details</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          <div><label className="label">Invoice Number</label><input value={invoice.invoiceNumber} onChange={e => update('invoiceNumber', e.target.value)} className="input-field" /></div>
          <div><label className="label">Invoice Date</label><input type="date" value={invoice.date} onChange={e => update('date', e.target.value)} className="input-field" /></div>
          <div><label className="label">Due Date</label><input type="date" value={invoice.dueDate} onChange={e => update('dueDate', e.target.value)} className="input-field" /></div>
        </div>
      </div>

      {/* From / To */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
        <div className="card">
          <h3 className="font-bold text-gray-800 mb-3">Your Business</h3>
          <div className="space-y-3">
            <div><label className="label">Business Name</label><input value={invoice.businessName} onChange={e => update('businessName', e.target.value)} className="input-field" placeholder="Your business name" /></div>
            <div><label className="label">Phone</label><input value={invoice.businessPhone} onChange={e => update('businessPhone', e.target.value)} className="input-field" placeholder="+260..." /></div>
            <div><label className="label">Email</label><input value={invoice.businessEmail} onChange={e => update('businessEmail', e.target.value)} className="input-field" placeholder="email@example.com" /></div>
            <div><label className="label">Address</label><input value={invoice.businessAddress} onChange={e => update('businessAddress', e.target.value)} className="input-field" placeholder="Lusaka, Zambia" /></div>
          </div>
        </div>
        <div className="card">
          <h3 className="font-bold text-gray-800 mb-3">Bill To (Client)</h3>
          <div className="space-y-3">
            <div><label className="label">Client Name</label><input value={invoice.clientName} onChange={e => update('clientName', e.target.value)} className="input-field" placeholder="Client or company name" /></div>
            <div><label className="label">Phone</label><input value={invoice.clientPhone} onChange={e => update('clientPhone', e.target.value)} className="input-field" placeholder="+260..." /></div>
            <div><label className="label">Address</label><input value={invoice.clientAddress} onChange={e => update('clientAddress', e.target.value)} className="input-field" placeholder="Client address" /></div>
          </div>
        </div>
      </div>

      {/* Line items */}
      <div className="card mb-4">
        <div className="flex items-center justify-between mb-4">
          <h2 className="font-bold text-gray-800">Items / Services</h2>
          <button onClick={addItem} className="text-primary text-sm font-medium flex items-center gap-1 hover:text-primary-dark">
            <Plus className="w-4 h-4" /> Add Item
          </button>
        </div>
        <div className="space-y-2">
          <div className="hidden sm:grid grid-cols-12 gap-2 text-xs font-semibold text-gray-500 px-1">
            <span className="col-span-6">Description</span>
            <span className="col-span-2 text-center">Qty</span>
            <span className="col-span-2 text-right">Unit Price (K)</span>
            <span className="col-span-2 text-right">Total</span>
          </div>
          {invoice.items.map((item, i) => (
            <div key={i} className="grid grid-cols-12 gap-2 items-center">
              <input value={item.description} onChange={e => updateItem(i, 'description', e.target.value)} className="input-field col-span-6" placeholder="Item or service description" />
              <input type="number" value={item.quantity} onChange={e => updateItem(i, 'quantity', e.target.value)} className="input-field col-span-2 text-center" min="1" />
              <input type="number" value={item.unitPrice} onChange={e => updateItem(i, 'unitPrice', e.target.value)} className="input-field col-span-2 text-right" placeholder="0.00" min="0" />
              <div className="col-span-1 text-right text-sm font-medium text-primary">
                {formatKwacha((parseFloat(item.unitPrice) || 0) * (parseFloat(item.quantity) || 0))}
              </div>
              {invoice.items.length > 1 && (
                <button onClick={() => removeItem(i)} className="col-span-1 text-red-400 hover:text-red-600 flex justify-center">
                  <Trash2 className="w-4 h-4" />
                </button>
              )}
            </div>
          ))}
        </div>

        {/* Totals */}
        <div className="mt-4 pt-4 border-t border-gray-100">
          <div className="flex justify-end">
            <div className="w-64 space-y-2">
              <div className="flex justify-between text-sm"><span className="text-gray-600">Subtotal</span><span className="font-medium">{formatKwacha(subtotal)}</span></div>
              <div className="flex items-center gap-2 text-sm">
                <input type="checkbox" checked={invoice.includeTax} onChange={e => update('includeTax', e.target.checked)} className="w-4 h-4" id="tax" />
                <label htmlFor="tax" className="text-gray-600">Include VAT</label>
                {invoice.includeTax && (
                  <input type="number" value={invoice.taxRate} onChange={e => update('taxRate', e.target.value)} className="input-field w-16 text-center py-1" style={{minHeight: 'auto'}} />
                )}
                {invoice.includeTax && <span className="text-gray-500">%</span>}
              </div>
              {invoice.includeTax && <div className="flex justify-between text-sm"><span className="text-gray-600">VAT ({invoice.taxRate}%)</span><span>{formatKwacha(tax)}</span></div>}
              <div className="flex justify-between font-bold text-base pt-2 border-t border-gray-200">
                <span className="text-primary">TOTAL</span>
                <span className="text-primary">{formatKwacha(total)}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Notes */}
      <div className="card mb-4">
        <label className="label">Notes (optional)</label>
        <textarea value={invoice.notes} onChange={e => update('notes', e.target.value)} className="textarea-field" rows={2} placeholder="Payment terms, bank details, thank you message..." />
      </div>

      <button onClick={generatePDF} className="btn-green w-full gap-2 text-base">
        <Download className="w-5 h-5" /> Download Invoice PDF
      </button>
    </div>
  );
}
