import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Receipt, Plus, Trash2, Download, ArrowLeft } from 'lucide-react';
import { formatKwacha } from '../lib/utils';
import useAuthStore from '../store/authStore';
import { Toast, useToast } from '../components/shared/SuccessToast';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function InvoiceGenerator() {
  const { userProfile } = useAuthStore();
  const { toast, show, hide } = useToast();
  const navigate = useNavigate();

  const [invoice, setInvoice] = useState({
    invoiceNumber: `INV-${Date.now().toString().slice(-5)}`,
    date: new Date().toISOString().split('T')[0],
    dueDate: '',
    businessName: userProfile?.businessName || '',
    businessPhone: '',
    businessEmail: '',
    businessAddress: '',
    clientName: '',
    clientPhone: '',
    clientAddress: '',
    items: [{ description: '', quantity: 1, unitPrice: '' }],
    notes: '',
    includeTax: false,
    taxRate: 16,
    momoPaymentDetails: '',
  });

  function update(field, value) {
    setInvoice(prev => ({ ...prev, [field]: value }));
  }

  function addItem() {
    setInvoice(prev => ({ ...prev, items: [...prev.items, { description: '', quantity: 1, unitPrice: '' }] }));
  }

  function removeItem(i) {
    setInvoice(prev => ({ ...prev, items: prev.items.filter((_, idx) => idx !== i) }));
  }

  function updateItem(i, field, value) {
    setInvoice(prev => {
      const items = [...prev.items];
      items[i] = { ...items[i], [field]: value };
      return { ...prev, items };
    });
  }

  const subtotal = invoice.items.reduce((sum, item) => sum + ((parseFloat(item.unitPrice) || 0) * (parseFloat(item.quantity) || 0)), 0);
  const tax = invoice.includeTax ? subtotal * (invoice.taxRate / 100) : 0;
  const total = subtotal + tax;

  function generatePDF() {
    const doc = new jsPDF();
    const primary = [27, 79, 114];
    const gold = [183, 149, 11];

    // Header
    doc.setFillColor(...primary);
    doc.rect(0, 0, 210, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont(undefined, 'bold');
    doc.text('INVOICE', 14, 16);
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Invoice #: ${invoice.invoiceNumber}`, 14, 24);
    doc.text(`Date: ${invoice.date}`, 14, 30);
    if (invoice.dueDate) doc.text(`Due: ${invoice.dueDate}`, 80, 30);

    // IMPUNGA branding
    doc.setFontSize(9);
    doc.setTextColor(180, 220, 255);
    doc.text('Generated by IMPUNGA', 150, 24);
    doc.text('impunga.vercel.app', 155, 30);

    // Business & Client info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('FROM:', 14, 48);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(invoice.businessName || 'Your Business Name', 14, 55);
    if (invoice.businessPhone) doc.text(`Tel: ${invoice.businessPhone}`, 14, 61);
    if (invoice.businessEmail) doc.text(invoice.businessEmail, 14, 67);
    if (invoice.businessAddress) doc.text(invoice.businessAddress, 14, 73);

    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('BILL TO:', 110, 48);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(10);
    doc.text(invoice.clientName || 'Client Name', 110, 55);
    if (invoice.clientPhone) doc.text(`Tel: ${invoice.clientPhone}`, 110, 61);
    if (invoice.clientAddress) doc.text(invoice.clientAddress, 110, 67);

    // Items table
    const tableRows = invoice.items.map(item => [
      item.description || '-',
      item.quantity,
      formatKwacha(parseFloat(item.unitPrice) || 0),
      formatKwacha((parseFloat(item.unitPrice) || 0) * (parseFloat(item.quantity) || 0)),
    ]);

    autoTable(doc, {
      startY: 85,
      head: [['Description', 'Qty', 'Unit Price', 'Total']],
      body: tableRows,
      headStyles: { fillColor: primary, textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 247, 249] },
      columnStyles: { 0: { cellWidth: 90 }, 1: { halign: 'center' }, 2: { halign: 'right' }, 3: { halign: 'right' } },
    });

    const finalY = doc.lastAutoTable.finalY + 8;

    // Totals
    doc.setFontSize(10);
    doc.text('Subtotal:', 140, finalY);
    doc.text(formatKwacha(subtotal), 196, finalY, { align: 'right' });

    if (invoice.includeTax) {
      doc.text(`VAT (${invoice.taxRate}%):`, 140, finalY + 7);
      doc.text(formatKwacha(tax), 196, finalY + 7, { align: 'right' });
    }

    doc.setFillColor(...primary);
    doc.rect(130, finalY + (invoice.includeTax ? 12 : 5), 70, 10, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont(undefined, 'bold');
    doc.text('TOTAL:', 134, finalY + (invoice.includeTax ? 19 : 12));
    doc.text(formatKwacha(total), 196, finalY + (invoice.includeTax ? 19 : 12), { align: 'right' });

    // Notes & Payment Info
    let yNotes = finalY + 30;
    if (invoice.momoPaymentDetails) {
      doc.setTextColor(...primary);
      doc.setFont(undefined, 'bold');
      doc.setFontSize(10);
      doc.text('Payment Instructions (Mobile Money):', 14, yNotes);
      doc.setTextColor(0, 0, 0);
      doc.setFont(undefined, 'normal');
      doc.setFontSize(9);
      doc.text(invoice.momoPaymentDetails, 14, yNotes + 7);
      yNotes += 17;
    }

    if (invoice.notes) {
      doc.setTextColor(0, 0, 0);
      doc.setFont(undefined, 'normal');
      doc.setFontSize(9);
      doc.text('Notes:', 14, yNotes);
      doc.text(invoice.notes, 14, yNotes + 7);
    }

    // Footer
    doc.setTextColor(150);
    doc.setFontSize(8);
    doc.text('Thank you for your business! | Generated by IMPUNGA — Start. Match. Build Zambia.', 105, 285, { align: 'center' });

    doc.save(`Invoice_${invoice.invoiceNumber}_${invoice.clientName || 'Client'}.pdf`);
    show('Invoice downloaded!');
  }

  return (
    <div className="max-w-4xl mx-auto pb-24 animate-fade-in">
      {toast && <Toast message={toast.message} type={toast.type} onClose={hide} />}

      

      {/* Invoice details */}
      <div className="bg-white/85 backdrop-blur-3xl border border-white/60 shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-3xl p-6 sm:p-8 mb-6 relative overflow-hidden">
        <h2 className="font-extrabold text-gray-800 mb-5 text-lg">Invoice Details</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-5 relative z-10">
          <div><label className="block text-sm font-semibold text-gray-700 mb-2">Invoice Number</label><input value={invoice.invoiceNumber} onChange={e => update('invoiceNumber', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm" /></div>
          <div><label className="block text-sm font-semibold text-gray-700 mb-2">Invoice Date</label><input type="date" value={invoice.date} onChange={e => update('date', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm" /></div>
          <div><label className="block text-sm font-semibold text-gray-700 mb-2">Due Date</label><input type="date" value={invoice.dueDate} onChange={e => update('dueDate', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm" /></div>
        </div>
      </div>

      {/* From / To */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
        <div className="bg-white/85 backdrop-blur-3xl border border-white/60 shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-3xl p-6 sm:p-8 relative overflow-hidden">
          <div className="absolute -right-16 -top-16 w-48 h-48 bg-green-200/20 rounded-full blur-3xl pointer-events-none" />
          <h3 className="font-extrabold text-gray-800 mb-5 text-lg relative z-10">Your Business</h3>
          <div className="space-y-4 relative z-10">
            <div><label className="block text-sm font-semibold text-gray-700 mb-2">Business Name</label><input value={invoice.businessName} onChange={e => update('businessName', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm" placeholder="Your business name" /></div>
            <div><label className="block text-sm font-semibold text-gray-700 mb-2">Phone</label><input value={invoice.businessPhone} onChange={e => update('businessPhone', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm" placeholder="+260..." /></div>
            <div><label className="block text-sm font-semibold text-gray-700 mb-2">Email</label><input value={invoice.businessEmail} onChange={e => update('businessEmail', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm" placeholder="email@example.com" /></div>
            <div><label className="block text-sm font-semibold text-gray-700 mb-2">Address</label><input value={invoice.businessAddress} onChange={e => update('businessAddress', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm" placeholder="Lusaka, Zambia" /></div>
            <div><label className="block text-sm font-semibold text-gray-700 mb-2">Mobile Money Payment Info (MTN/Airtel/Zamtel)</label><input value={invoice.momoPaymentDetails} onChange={e => update('momoPaymentDetails', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-dashed border-indigo-200 rounded-xl px-4 py-3 text-gray-850 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm font-bold bg-indigo-50/10" placeholder="e.g. MTN MoMo - 0961122334" /></div>
          </div>
        </div>
        <div className="bg-white/85 backdrop-blur-3xl border border-white/60 shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-3xl p-6 sm:p-8 relative overflow-hidden">
          <div className="absolute -left-16 -top-16 w-48 h-48 bg-blue-200/20 rounded-full blur-3xl pointer-events-none" />
          <h3 className="font-extrabold text-gray-800 mb-5 text-lg relative z-10">Bill To (Client)</h3>
          <div className="space-y-4 relative z-10">
            <div><label className="block text-sm font-semibold text-gray-700 mb-2">Client Name</label><input value={invoice.clientName} onChange={e => update('clientName', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-500 transition-all shadow-sm" placeholder="Client or company name" /></div>
            <div><label className="block text-sm font-semibold text-gray-700 mb-2">Phone</label><input value={invoice.clientPhone} onChange={e => update('clientPhone', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-500 transition-all shadow-sm" placeholder="+260..." /></div>
            <div><label className="block text-sm font-semibold text-gray-700 mb-2">Address</label><input value={invoice.clientAddress} onChange={e => update('clientAddress', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500/30 focus:border-blue-500 transition-all shadow-sm" placeholder="Client address" /></div>
          </div>
        </div>
      </div>

      {/* Line items */}
      <div className="bg-white/85 backdrop-blur-3xl border border-white/60 shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-3xl p-6 sm:p-8 mb-6 relative overflow-hidden">
        <div className="flex items-center justify-between mb-5">
          <h2 className="font-extrabold text-gray-800 text-lg">Items / Services</h2>
          <button onClick={addItem} className="bg-green-50 text-green-700 hover:bg-green-100 text-sm font-bold flex items-center gap-1.5 px-4 py-2 rounded-xl transition-colors">
            <Plus className="w-4 h-4" /> Add Item
          </button>
        </div>
        <div className="space-y-3">
          <div className="hidden sm:grid grid-cols-12 gap-3 text-xs font-bold text-gray-400 uppercase tracking-wider px-1">
            <span className="col-span-6">Description</span>
            <span className="col-span-2 text-center">Qty</span>
            <span className="col-span-2 text-right">Unit Price (K)</span>
            <span className="col-span-2 text-right">Total</span>
          </div>
          {invoice.items.map((item, i) => (
            <div key={i} className="grid grid-cols-12 gap-3 items-center bg-gray-50/50 p-2 rounded-2xl">
              <input value={item.description} onChange={e => updateItem(i, 'description', e.target.value)} className="col-span-12 sm:col-span-6 w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm" placeholder="Item or service description" />
              <input type="number" value={item.quantity} onChange={e => updateItem(i, 'quantity', e.target.value)} className="col-span-4 sm:col-span-2 w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm text-center" min="1" />
              <input type="number" value={item.unitPrice} onChange={e => updateItem(i, 'unitPrice', e.target.value)} className="col-span-4 sm:col-span-2 w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-xl px-4 py-3 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm text-right" placeholder="0.00" min="0" />
              <div className="col-span-3 sm:col-span-1 text-right text-sm font-extrabold text-green-700">
                {formatKwacha((parseFloat(item.unitPrice) || 0) * (parseFloat(item.quantity) || 0))}
              </div>
              {invoice.items.length > 1 && (
                <button onClick={() => removeItem(i)} className="col-span-1 sm:col-span-1 text-red-400 hover:text-red-600 hover:bg-red-50 p-2 rounded-xl flex justify-center transition-colors">
                  <Trash2 className="w-5 h-5" />
                </button>
              )}
            </div>
          ))}
        </div>

        {/* Totals */}
        <div className="mt-6 pt-6 border-t border-gray-100/80">
          <div className="flex justify-end">
            <div className="w-full sm:w-72 space-y-3">
              <div className="flex justify-between text-sm"><span className="text-gray-500 font-semibold">Subtotal</span><span className="font-extrabold text-gray-800">{formatKwacha(subtotal)}</span></div>
              <div className="flex items-center justify-between text-sm">
                <div className="flex items-center gap-2">
                  <input type="checkbox" checked={invoice.includeTax} onChange={e => update('includeTax', e.target.checked)} className="w-4 h-4 rounded border-gray-300 text-green-600 focus:ring-green-500" id="tax" />
                  <label htmlFor="tax" className="text-gray-500 font-semibold cursor-pointer">Include VAT</label>
                </div>
                {invoice.includeTax && (
                  <div className="flex items-center gap-1">
                    <input type="number" value={invoice.taxRate} onChange={e => update('taxRate', e.target.value)} className="w-16 bg-white/50 border border-gray-200 rounded-lg px-2 py-1 text-center font-bold text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500" />
                    <span className="text-gray-500 font-bold">%</span>
                  </div>
                )}
              </div>
              {invoice.includeTax && <div className="flex justify-between text-sm"><span className="text-gray-500 font-semibold">VAT ({invoice.taxRate}%)</span><span className="font-extrabold text-gray-800">{formatKwacha(tax)}</span></div>}
              <div className="flex justify-between font-extrabold text-xl pt-4 border-t border-gray-200">
                <span className="text-gray-800">TOTAL</span>
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-green-600 to-emerald-600">{formatKwacha(total)}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Notes */}
      <div className="bg-white/85 backdrop-blur-3xl border border-white/60 shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-3xl p-6 sm:p-8 mb-8 relative overflow-hidden">
        <label className="block text-sm font-semibold text-gray-700 mb-2">Notes (optional)</label>
        <textarea value={invoice.notes} onChange={e => update('notes', e.target.value)} className="w-full bg-white/50 backdrop-blur-sm border border-gray-200 rounded-2xl px-5 py-4 text-gray-800 focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 transition-all shadow-sm resize-none" rows={2} placeholder="Payment terms, bank details, thank you message..." />
      </div>

      <button onClick={generatePDF} className="w-full bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white font-bold py-4 rounded-2xl transition-all shadow-lg shadow-green-500/30 disabled:opacity-50 active:scale-[0.98] flex items-center justify-center gap-2 text-lg">
        <Download className="w-5 h-5" /> Download Invoice PDF
      </button>
    </div>
  );
}
