import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, Presentation, Download, RefreshCw, Sparkles } from 'lucide-react';
import { useAI } from '../hooks/useAI';
import { jsPDF } from 'jspdf';
import ErrorMessage from '../components/shared/ErrorMessage';
import LoadingSpinner from '../components/shared/LoadingSpinner';
import AIResponse from '../components/shared/AIResponse';

export default function PitchDeckGenerator() {
  const [pipelineData, setPipelineData] = useState(null);
  const [deckContent, setDeckContent] = useState('');
  const { generatePitchDeck, loading, error } = useAI();
  const navigate = useNavigate();

  useEffect(() => {
    const stored = localStorage.getItem('impunga_idea_pipeline');
    if (stored) {
      const data = JSON.parse(stored);
      setPipelineData(data);
      if (!deckContent && !loading) {
        handleGenerate(data);
      }
    }
  }, []);

  async function handleGenerate(data) {
    if (!data) return;
    try {
      const result = await generatePitchDeck(data);
      setDeckContent(result);
    } catch (err) {
      console.error(err);
    }
  }

  function handleDownloadPDF() {
    if (!deckContent) return;
    const doc = new jsPDF();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('Investor Pitch Deck', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text('Generated by IMPUNGA', 105, 28, { align: 'center' });
    
    doc.setDrawColor(200);
    doc.line(20, 35, 190, 35);
    
    let yPos = 45;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(0);
    
    const lines = doc.splitTextToSize(deckContent.replace(/\\*\\*/g, ''), 170);
    for (let i = 0; i < lines.length; i++) {
      if (yPos > 280) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(lines[i], 20, yPos);
      yPos += 5;
    }
    
    doc.save('Pitch_Deck.pdf');
  }

  if (!pipelineData) {
    return (
      <div className="max-w-4xl mx-auto pb-24 animate-fade-in text-center pt-20">
        <h2 className="text-2xl font-bold text-gray-800 mb-4">No Validated Idea Found</h2>
        <p className="text-gray-500 mb-8">Please validate your business idea first to generate a pitch deck.</p>
        <Link to="/idea-validator" className="bg-yellow-500 text-white px-6 py-3 rounded-xl font-bold">Go to Idea Validator</Link>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto pb-24 animate-fade-in">
      <button onClick={() => navigate(-1)} className="inline-flex items-center gap-2 text-sm font-medium text-gray-500 hover:text-gray-800 mb-6 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Back
      </button>

      <div className="mb-8">
        <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight mb-2">Pitch Deck Generator</h1>
        <p className="text-gray-500 font-medium">10-slide investor presentation tailored to your business</p>
      </div>

      <div className="bg-white/85 border border-white/60 shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-3xl p-6 sm:p-8 relative overflow-hidden">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 text-indigo-600">
            <LoadingSpinner size="lg" />
            <p className="mt-4 font-medium animate-pulse">Structuring your 10-slide pitch deck...</p>
          </div>
        ) : error ? (
          <ErrorMessage message={error} />
        ) : deckContent ? (
          <div className="animate-slide-up">
            <div className="prose prose-indigo max-w-none mb-8 bg-gray-50 p-6 rounded-2xl">
              <AIResponse content={deckContent} />
            </div>
            <div className="flex gap-4">
              <button onClick={handleDownloadPDF} className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold px-6 py-3 rounded-xl transition-all shadow-md shadow-indigo-600/20 active:scale-95">
                <Download className="w-5 h-5" /> Download PDF
              </button>
              <button onClick={() => handleGenerate(pipelineData)} className="flex items-center gap-2 bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 font-bold px-6 py-3 rounded-xl transition-all active:scale-95">
                <RefreshCw className="w-5 h-5" /> Regenerate
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}
