import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, Presentation, Download, RefreshCw, Sparkles } from 'lucide-react';
import { useAI } from '../hooks/useAI';
import { jsPDF } from 'jspdf';
import pptxgen from 'pptxgenjs';
import { stripMarkdown } from '../lib/stripMarkdown';
import ErrorMessage from '../components/shared/ErrorMessage';
import LoadingSpinner from '../components/shared/LoadingSpinner';
import AIResponse from '../components/shared/AIResponse';

export default function PitchDeckGenerator() {
  const [pipelineData, setPipelineData] = useState(null);
  const [deckContent, setDeckContent] = useState('');
  const { generatePitchDeck, loading, error } = useAI();
  const navigate = useNavigate();

  useEffect(() => {
    const stored = localStorage.getItem('impunga_idea_pipeline');
    if (stored) {
      const data = JSON.parse(stored);
      setPipelineData(data);
      if (!deckContent && !loading) {
        handleGenerate(data);
      }
    }
  }, []);

  async function handleGenerate(data) {
    if (!data) return;
    try {
      const result = await generatePitchDeck(data);
      setDeckContent(result);
    } catch (err) {
      console.error(err);
    }
  }

  function handleDownloadPDF() {
    if (!deckContent) return;
    const doc = new jsPDF();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('Investor Pitch Deck', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text('Generated by IMPUNGA', 105, 28, { align: 'center' });
    
    doc.setDrawColor(200);
    doc.line(20, 35, 190, 35);
    
    let yPos = 45;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(0);
    
    const cleanContent = stripMarkdown(deckContent);
    const lines = doc.splitTextToSize(cleanContent, 170);
    for (let i = 0; i < lines.length; i++) {
      if (yPos > 280) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(lines[i], 20, yPos);
      yPos += 5;
    }
    
    doc.save('Pitch_Deck.pdf');
  }

  async function handleDownloadPPT() {
    if (!deckContent) return;
    
    const pres = new pptxgen();
    pres.layout = 'LAYOUT_16x9';
    
    // Cover slide
    let coverSlide = pres.addSlide();
    coverSlide.background = { color: "F3F4F6" };
    coverSlide.addText("Investor Pitch Deck", { x: '10%', y: '40%', w: '80%', h: 1, fontSize: 44, bold: true, align: "center", color: "1F2937" });
    coverSlide.addText("Generated by IMPUNGA", { x: '10%', y: '60%', w: '80%', h: 1, fontSize: 20, align: "center", color: "6B7280" });
    
    // Parse content
    const cleanContent = stripMarkdown(deckContent);
    const sections = cleanContent.split(/\n\n+/);
    
    sections.forEach((section) => {
      if (section.trim().length > 0) {
        let s = pres.addSlide();
        
        const lines = section.split('\n');
        const title = lines[0].trim();
        const body = lines.slice(1).join('\n').trim();
        
        s.addText(title, { x: 0.5, y: 0.5, w: '90%', h: 0.8, fontSize: 28, bold: true, color: '1F2937' });
        
        if (body.length > 0) {
           s.addText(body, { x: 0.5, y: 1.5, w: '90%', h: 3.5, fontSize: 16, color: '4B5563', valign: 'top' });
        }
      }
    });

    pres.writeFile({ fileName: "Pitch_Deck.pptx" });
  }

  if (!pipelineData) {
    return (
      <div className="max-w-4xl mx-auto pb-24 animate-fade-in text-center pt-20">
        <h2 className="text-2xl font-bold text-gray-800 mb-4">No Validated Idea Found</h2>
        <p className="text-gray-500 mb-8">Please validate your business idea first to generate a pitch deck.</p>
        <Link to="/idea-validator" className="bg-yellow-500 text-white px-6 py-3 rounded-xl font-bold">Go to Idea Validator</Link>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto pb-24 animate-fade-in text-left">
      

      <div className="bg-white/85 border border-white/60 shadow-[0_8px_30px_rgb(0,0,0,0.06)] rounded-3xl p-6 sm:p-8 relative overflow-hidden">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 text-indigo-600">
            <LoadingSpinner size="lg" />
            <p className="mt-4 font-medium animate-pulse">Structuring your 10-slide pitch deck...</p>
          </div>
        ) : error ? (
          <ErrorMessage message={error} />
        ) : deckContent ? (
          <div className="animate-slide-up">
            <div className="prose prose-indigo max-w-none mb-8 bg-gray-50 p-6 rounded-2xl">
              <AIResponse content={deckContent} />
            </div>
            <div className="flex gap-4">
              <button onClick={handleDownloadPDF} className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold px-6 py-3 rounded-xl transition-all shadow-md shadow-indigo-600/20 active:scale-95">
                <Download className="w-5 h-5" /> Download PDF
              </button>
              <button onClick={handleDownloadPPT} className="flex items-center gap-2 bg-orange-500 hover:bg-orange-600 text-white font-bold px-6 py-3 rounded-xl transition-all shadow-md shadow-orange-500/20 active:scale-95">
                <Download className="w-5 h-5" /> Download PPTX
              </button>
              <button onClick={() => handleGenerate(pipelineData)} className="flex items-center gap-2 bg-white border border-gray-200 text-gray-700 hover:bg-gray-50 font-bold px-6 py-3 rounded-xl transition-all active:scale-95">
                <RefreshCw className="w-5 h-5" /> Regenerate
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}
